<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');

    $_lightboxConfig = Mage::getStoreConfig('easy_lightbox/general');
    /* Main Image Size */
    if (strstr($_lightboxConfig['mainImageSize'], '_')) {
        $mainImageSize = explode('_', $_lightboxConfig['mainImageSize'], 2);
    } else {
        $mainImageSize = array(265, 265);
    }
    $configEntry = (Mage::helper('tools/product')->isArtwork($_product) == true ? 'popupImageSizeArtwork' : 'popupImageSize');
    /* Popup Image Size */
    if (strstr($_lightboxConfig[$configEntry], '_')) {
        $popupImageSize = explode('_', $_lightboxConfig[$configEntry], 2);
    } else {
        $popupImageSize = array(0, 0);
    } 
    /* Additional Images Size */
    if (strstr($_lightboxConfig['additionalImageSize'], '_')) {
        $additionalImageSize = explode('_', $_lightboxConfig['additionalImageSize'], 2);
    } else {
        $additionalImageSize = array(60, 60);
    }
    
    $image = $this->helper('catalog/image')->init($_product, 'image');
    if ($popupImageSize[0] > 0) {
        $image = $this->helper('catalog/image')->init($_product, 'image')->resize($popupImageSize[0], $popupImageSize[1]);
    }
    
    // est-ce que le produit est un "printed-on-demand"
    $isPod = Mage::helper('easylife_switcher/product')->isPrintOnDemand($_product);

?>

<?php /* On déclare un conteneur pour pouvoir déclater la div suivante en position relative et pouvoir de cette façon placer le bandeau exclusif si il y a besoin */ ?>
<div class="easylightbox-media-conteneur">
<?php if(!$_lightboxConfig['defaulzoom']): ?>

<?php
	$maintitle = $this->htmlEscape($_product->getImageLabel());
	if(($_lightboxConfig['productName'] != 0) && empty($maintitle)):
	        $maintitle  = $_product->getName();
	endif;
?>
    <?php if( $isPod ) : ?>

    <canvas id="main-canvas" width="265" height="265"></canvas>

    <?php else : ?>

<a href="<?php echo $image; ?>" 
    rel="lightbox[rotation]" 
    title="<?php echo $maintitle ;?>"
    onclick="return false;"
>
<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($mainImageSize[0], $mainImageSize[1]); ?>" alt="<?php echo $this->htmlEscape($_product->getImageLabel());?>" /></a>

    <?php endif ?>

<?php else: ?>

<p class="product-image-zoom">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image')
    ?>
</p>
<p class="a-center" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>

<div class="image-zoom" id="track_outer">
    <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>
<script type="text/javascript">
    Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    });
</script>

<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 0): ?>

<div class="more-views">
    <h4><?php echo $this->__('More Views') ?></h4>
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
	<?php
	$subtitle = $this->htmlEscape($_image->getLabel());
	if(($_lightboxConfig['productName'] != 0) && empty($subtitle)):
	        $subtitle  = $_product->getName();
	endif;
	?>
    <li>
        <?php if( $isPod): ?>

        <img style="cursor:pointer;" class="simple-product" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($additionalImageSize[0], $additionalImageSize[1]); ?>" alt="<?php echo $subtitle; ?>" title="<?php echo $subtitle; ?>" onclick="spConfig.changeMediaOnClick('<?php echo $subtitle; ?>', <?php echo $this->getProduct()->getID(); ?>);" />

        <?php else: ?>

        <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($popupImageSize[0], $popupImageSize[1]); ?>" 
            rel="lightbox[rotation]" 
            title="<?php echo $subtitle; ?>"
            onclick="return false;"
        ><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($additionalImageSize[0], $additionalImageSize[1]); ?>" alt="<?php echo $subtitle; ?>"
        /></a>

        <?php endif; ?>
    </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<?php /* Si l'article est exclusif on place le bandeau exclu pour le signaler */ ?>
<?php if ($_product->getExclusive() != 0) :?><div class="corner-exclu-shop"></div><?php endif; ?>
</div>
